rho,	rhou,	rhov,	rhoet
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
inf,	inf,	inf,	inf
